### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Poil** [puzzle/environmate#1]
Hi,

I was reading your code when a typo :

Missing a "R" line 15 of environmate/blob/master/lib/environmate/user.rb 

```
Envionmate.log.info("Xmpp user found #{@xmpp_user}")
```

**Comment by ZeroPointEnergy** [comment]
Thank, fixed it.

It's in a code part we don't use at the moment so I completely missed that. Will have to refactor that and write some tests around it :-)
